{% set name = "smithy" %}
{% set version = "1.53.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/smithy-lang/smithy/archive/{{ version }}.tar.gz
  sha256: 80d86a53b1ae469312ab777c439b4e0ae9f7c1265d9edec90b0bb78330795134

build:
  noarch: generic
  number: 0

requirements:
  build:
    - findutils
    - openjdk =21
    - sed
  run:
    - openjdk

test:
  commands:
    - smithy --help

about:
  home: https://github.com/smithy-lang/smithy
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: Smithy is a protocol-agnostic interface definition language and set of tools for generating clients, servers, and documentation for any programming language.
  dev_url: https://github.com/smithy-lang/smithy

extra:
  recipe-maintainers:
    - danielnachun
