context:
  version: "1.57.0"

package:
  name: smithy
  version: ${{ version }}

source:
  url: https://github.com/smithy-lang/smithy/archive/${{ version }}.tar.gz
  sha256: 1f3eda9e0cceebcd4de4887caee57f9f9a07472c9feb105ad19e19e5a0cbe4da

build:
  number: 0
  noarch: generic

requirements:
  host:
    - findutils
    - openjdk =21
    - sed
  run:
    - openjdk

tests:
  - script:
      - smithy --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: Smithy is a protocol-agnostic interface definition language and set of tools for generating clients, servers, and documentation for any programming language.
  homepage: https://github.com/smithy-lang/smithy
  repository: https://github.com/smithy-lang/smithy

extra:
  recipe-maintainers:
    - danielnachun
