context:
  version: "1.69.0"

package:
  name: smithy
  version: ${{ version }}

source:
  url: https://github.com/smithy-lang/smithy/archive/${{ version }}.tar.gz
  sha256: 2ed0a6bc5ae55e64c6e29087fce938b3c65489c6893c8b34cb399c7609b07a01

build:
  number: 0
  noarch: generic

requirements:
  host:
    - findutils
    - openjdk =21
    - sed
  run:
    - openjdk

tests:
  - script:
      - smithy --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: Smithy is a protocol-agnostic interface definition language and set of tools for generating clients, servers, and documentation for any programming language.
  homepage: https://github.com/smithy-lang/smithy
  repository: https://github.com/smithy-lang/smithy

extra:
  recipe-maintainers:
    - danielnachun
